### ISSUE TITLE
EVM

### ISSUE THREAD

**Issue by faddat** [CosmosContracts/juno#12]
So I tested out the Stargate version of the EVM module yesterday.

Things went well!

It's my understanding that Ethereum 1.10.* much much faster than 1.9.* so I've been trying to get that in by default.

It's not done yet, seem to need to refactor the stuff that supports Access list. 

GitHub.om/faddat/ethermint

It is in the latest-eth-sleepy branch.  

Let me know what ya think :), any assistance with that is of course greatly appreciated.

**Comment by blockcreators** [comment]
I think we will be waiting for an official supported version from:
https://github.com/cosmos/ethermint
Current estimates last I checked were the end of 2021.
I will check out your repo though :)

This is also why we are waiting on wasm v1 (hopefully late June) so that it will be supported going forward.
https://github.com/CosmWasm/cosmwasm

**Comment by faddat** [comment]
This is sensible.

**Comment by faddat** [comment]
closing per discussion
