### ISSUE TITLE
Consider a Bug Bounty program

### ISSUE THREAD

**Issue by elsehow** [CosmosContracts/juno#125]
Running CosmWasm in a permissionless state on a public blockchain, we should anticipate critical security vulnerabilities. While #124 provides some expectations about how disclosure happens, a bug bounty program can be helpful in guiding security researchers toward the official disclosure process; in effect, bug bounty programs make the risk-adjusted return of exploitation higher through the official channels than through crime.

As an example, [Cosmos has a HackerOne program](https://hackerone.com/cosmos?type=team). We could consider something similar, and reserve some amount of the community pool to fund the program.

**Comment by blockcreators** [comment]
@elsehow 
We were creating this, thoughts?
https://github.com/CosmosContracts/testnets/blob/main/uni/ATTACK.md

**Comment by elsehow** [comment]
@blockcreators Cool idea! I would recommend specifying explicitly that people should *not* disclose, tweet about, etc the attacks they find. They should *only* report them to meow and dimi. You can borrow language from https://github.com/CosmosContracts/juno/blob/main/SECURITY.md

**Comment by faddat** [comment]
Sers,

I strongly support this initiative and I want to make absolutely certain that the Juno bug bounty does not end up net harmful to wasm or cosmos ecosystem security by being a complete (security and economic) waste of time and effort like the Security.md at https://github.com/tendermint/tendermint.

After 18 days of waiting, the live exploit that my team and I spent our time documenting was pish poshed away and we were told that it was a "known issue" based on a github issue from 2018, before the transaction type used to attack sentinel (to this day, afaik, in fact if I had this to do over again, and more time for a retrospective,

1) 42 series chains withj ibc enabled are universally vulnerable to the usage of malformed client updates by an attacker in order to push the total traffic into the terabytes per day.

2) If we examine the reporting burden for the tendermint/tendermint security.md, we can see that for attackers looking to extract economic value from networks by various means, it is almost certain that any significant attack's economic value will exceed $5000.

**translation** we do not care. 

3) In order to save time and encourage people to use their time and energy to contribute to security in cosmwasm, the cosmos-sdk, ibc, and tendermint, we should give a hard think on weather we are willing to:

* commit to a turnaround time <12h
* **pay** non-spam / legit submissions in an automatic fashion (no, I don't mean that we have machines pay humans, I mean that humans pay machines)

4) We should discuss this matter w/ others implementing ibc

**Comment by faddat** [comment]
PS:  I keep thinking about how to **best** do this.  Certainly that is not h1 with maybe the key thing is that we talk to researchers.

**Comment by elsehow** [comment]
I agree that bug bounty programs are often frustrating in practice. (Apple's is notorious).

A common joke in security is that [smart contracts are self-funding bug bounties](https://twitter.com/pinboard/status/1399061177783623683). Perhaps this would actually be the best form for a bug bounty on juno.

At any time, well-known "honeypot" contracts can challenge participants to do some variety of attacks (e.g., double-spend), with a known $JUNO reward if they can do it. People can then disclose their vulnerability through the process to get another (perhaps matching) sum of $JUNO.

Some questions on my mind:

- What set of attacks would we want those honeypots to test against?
- What could a honeypot like this definitely *not* be able to test for?
