### ISSUE TITLE
Note to validators

### ISSUE THREAD

**Issue by faddat** [CosmosContracts/juno#67]
Hi, 

I'm operating a relayer.  If you are operating a validator, it is very important that you:

`systemctl enable systemd-timesyncd`

please. 

If you do not, there are time drift errors, and well, the Hermes default of five seconds is really pretty generous.

**Comment by ericjohncarlson** [comment]
Correct time is crucial for any participating node. 

In addition to the discord, I was going to create a PR to add this to the pre-requisites page of /validators/getting-setup page in the docs.  However, if Ubuntu LTS is the default assumption in the documentation, I believe `timesyncd` is enabled and active by default.  

It may be still worth including in the pre-reqs as a double check for installs outside of ubuntu LTS.  Another option I've used elsewhere is just forcing the install of `chrony` since that will work across distributions, is lightweight, and defaults to pool.ntp.org servers.
