### ISSUE TITLE
Remove myself and Notional from this repository

### ISSUE THREAD

**Issue by faddat** [CosmosContracts/juno#725]
Hey guys,

I wish I could say that it's been a good run, but numerous recent events have fully convinced me that Juno and I / Notional are no longer a good fit for one another.  

I think that I can leave the org myself, I'm going to work on that now.  

I'd like to be clear that while the straw that broke the camels back was knowing full well that I'm one of the longest term contributors here and that I'm not being compensated in any way for work on Juno, and getting this:

https://github.com/CosmosContracts/juno/pull/707

<img width="843" alt="Screenshot 2023-06-22 at 5 26 57 AM" src="https://github.com/CosmosContracts/juno/assets/7142025/9ff37b85-d6f5-4c2c-930e-f47905cc5f09">

I do understand fully that's how leadership is going here at Juno right now but it's my opinion that contributors shouldn't be treated in that manner.  

Had this been the first time, I'd not worry about it.  

Please don't delete this or anything, I would like the reasons for my / Notional's departure as unpaid contributors to be known.

![Screenshot_20230622-102337](https://github.com/CosmosContracts/juno/assets/7142025/dd608fbe-2d7b-4066-97a6-cdc2b369fe12)
![Screenshot_20230622-102343](https://github.com/CosmosContracts/juno/assets/7142025/e927e00a-7122-4cc3-a8f5-e66d6e10bb3e)
![Screenshot_20230622-102414](https://github.com/CosmosContracts/juno/assets/7142025/929c3ae7-00da-4845-8e66-c1e90d06aaf8)

I understand that Rarma's been helping in a working group to bloster the future of the chain.

![Screenshot_20230622-103926](https://github.com/CosmosContracts/juno/assets/7142025/9c60161a-159d-4655-8078-35d4cc7a552d)

I forgot somebody's name that was my crime.  Confusing two names. National has received no payment from Juno since fall of 22. The proposal to suspend payments to contributors did not pass, you can find it here:

https://daodao.zone/dao/juno1gpwekludv6vu8pkpnp2hwwf7f84a7mcvgm9t2cvp92hvpxk07kdq8z4xj2/proposals/A18

It was verbally communicated to me and my team members repeatedly that this would change when best in contracts were put in place, and most certainly our team does not mind accepting vested payments.

That never happened.

So the governance of this governance chain is off the rails. As far as I understand it, core 1 is also acting in open contravention of proposal 64, which prohibited core one from funding proprietary software in any form.

I'm a mere unpaid contributor here, and it's been made clear that the folks shaping junos future, feel I'm a net loss to the work, and are encouraging the cosmos community to "ask questions about how notional is funded".

And that's fine and people can ask and I answer too and I believe it's absolutely possible to say hey you know Eunice took that guy's name their names are really similar, without a long string of four letter words and such.

Core 1 members are very clear.

https://twitter.com/max_maxsolo/status/1668220253883465731

Max is a member of the core one DAO, and was recently vested 400,000 Juno.

I still wish the project well, and wish everyone at Juno all the best in their endeavors.

**Comment by faddat** [comment]
I was successful in leaving the organization.  

To ensure the smallest possible burden on the codeowners, including those who haven't been active here in months, I will ask our team members to remove themselves as well.

**Comment by elix1er** [comment]
sheesh, max got vested 400k juno ? seems fair 
GG & congrats to him, 
he indeed seems to be very active and responsive for the community, for a long time.

But... i have to add something, _a buddy of mine asked me to do so._

i saw this guy onboarding people from Terra nonstop, helping projects and their devs to onboard Juno faster via DMs, doing devrel stuff, saw weeks of daily activity him online, screensharing live in discord for countless hours, helping ppl when they were stuck at any RUST/WASM/Cosmos/IBC related questions regarding Juno. Including help for the massive influx of refugees rekt by UST depeg event, if in Juno channel or DM, that dev told me.

Obviously does need a bit time, to learn new cosmwasm std / storage versions + 
using cosmjs and IBC first time, people say, 
after coming over to bigger cosmos, 
from that pre-depeg Terra Ecosystem bubble island with its:
- own libs, wallets, tooling, stoneage cosmwasm VM version.

At beginning, there was a Kevin Garrison and some guy called Blockcreator,
that pitched the meantioned buddy of mine into Juno by promising  a quarterly compensation.
The second payroll never arrived, he said.  My buddy didnt deliver shit, they said. At all. 
Because they couldn't see code on github they said. 

Cuz Jake and Jack and Max and mr. UK highlander and godknowswhoelsewasonthatmultisig of legacy daodao core-1 .... 
nobody did even put a prop up for voting, regarding Q2 aka second compensation for all the efforts. 

Lack of compensation or any form of income at all, no savings due to wiped net-worth,
enfored him to jump from project to project and do multiple gigs at the same time, he told me.

So he couldnt deliver under pressure, as life and bills do NOT halt, like some chains sometimes right?

Anyways, whatever, however, may god bless everyone out there. 
Anywys, this text is just written down without beautifier or GPTifier like most onchain prop creators out there ;-) 
I dont care right now about my grammar or bad wording cuz im not UK or US guy with EN as motherlanguage.

Me neither him, both, do not even care anymore, **hope in cosmos and especially JUNO is deadly wiped**,
and happiness exclusively exist only for the lucky players here, like the
- OG validators, 
- (co) founders and people in charge
- some lucky top contributors 
- "community chain" core-leaders
- and DAODAODAODAO metadreamverse believers breathing hopium

#back2web2 is the way to go now.
this market is fking up quite a lot other people.
INCLUDING TOP NOTCH devs with HIGH git output frequency too.

> non-juno-related, but relevant IMHO:
     .. thinking about Larry0x for example, some A+ fullblood FOSS'er, absolute gem, top engineer, great code, STILL (!!) 

according to his tweets, starving to death, financial apparently got hit,
ultra low-end compensation compared to the quality output, 
that guy must be tripple rektified DUE TO pushing open source code contributions out..
without monetarisation options at all,  sending some hopium towards him and all others that feel what ive wrote here.

Experiment failed -
Lifes getting seriously rekt - 
And it is a goddamn sad reality. 

~ Signed, _some average joe_

**Comment by dimiandre** [comment]
done, thanks for the work did so far.

**Comment by faddat** [comment]
Core 1's Sif letter:

https://docs.google.com/document/d/1N9hUQgQz5O8OBlSPhhTQ50JUDnOlJQzCOuPa0PX-n2c/edit?usp=drivesdk
